# Generated by Django 3.2.8 on 2021-12-22 12:24

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=50)),
                ('image_url', models.CharField(blank=True, max_length=500)),
                ('job_location', models.CharField(max_length=50)),
                ('job_description', tinymce.models.HTMLField(blank=True, null=True)),
                ('responsibility', tinymce.models.HTMLField(blank=True, null=True)),
                ('skillset', tinymce.models.HTMLField(blank=True, null=True)),
                ('additional', tinymce.models.HTMLField(blank=True, null=True)),
                ('internship', models.BooleanField(default=False, verbose_name='Internship')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 13 digits allowed.", regex='^\\+?1?\\d{10,13}$')])),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('message', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Give your title')),
                ('price', models.CharField(max_length=10, verbose_name='Enter Price')),
                ('availability', models.BooleanField(verbose_name='Available or Not')),
                ('model_number', models.CharField(blank=True, max_length=50)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='upload/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='upload/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='upload/')),
                ('automatic', models.BooleanField(default=False, verbose_name='Automatic or Manual')),
                ('weight', models.CharField(blank=True, max_length=50)),
                ('plc_control', models.BooleanField(default=False, verbose_name='PLC Control')),
                ('computerized', models.BooleanField(default=False, verbose_name='Computerized or Manual')),
                ('supply_ability', models.BooleanField(default=False, verbose_name='Supply Ability')),
                ('detail', tinymce.models.HTMLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('message', models.TextField(max_length=250)),
                ('gmail', models.EmailField(max_length=50, null=True)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(blank=True, null=True, upload_to='upload/')),
            ],
        ),
    ]
