# Generated by Django 3.2.8 on 2021-12-05 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cnc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Give your title')),
                ('manufacturing_date', models.DateField(verbose_name='Add Manufacturing date')),
                ('price', models.IntegerField(verbose_name='Enter Price')),
                ('availability', models.BooleanField(verbose_name='Available or Not')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('title', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cnc.product')),
            ],
        ),
    ]
