# Generated by Django 3.2.8 on 2022-01-04 20:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cnc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_book',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='career',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='career',
            name='designation',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='career',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='career',
            name='job_location',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='careerapplication',
            name='contact_details',
            field=models.TextField(blank=True, null=True, verbose_name='Contact Details'),
        ),
        migrations.AlterField(
            model_name='careerapplication',
            name='date_upload',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='careerapplication',
            name='department',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='careerapplication',
            name='gmail_id',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='careerapplication',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='careerapplication',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='upload/'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='date_contact',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='automatic',
            field=models.BooleanField(default=False, null=True, verbose_name='Automatic or Manual'),
        ),
        migrations.AlterField(
            model_name='product',
            name='computerized',
            field=models.BooleanField(default=False, null=True, verbose_name='Computerized or Manual'),
        ),
        migrations.AlterField(
            model_name='product',
            name='plc_control',
            field=models.BooleanField(default=False, null=True, verbose_name='PLC Control'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=10, null=True, verbose_name='Enter Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='supply_ability',
            field=models.BooleanField(default=False, null=True, verbose_name='Supply Ability'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=50, null=True, verbose_name='Give your title'),
        ),
        migrations.AlterField(
            model_name='review',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
