# Generated by Django 3.2.8 on 2021-12-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnc', '0002_product_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='manufacturing_date',
        ),
        migrations.AddField(
            model_name='product',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='upload/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='upload/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='upload/'),
        ),
        migrations.AddField(
            model_name='product',
            name='model_numbeer',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
