# Generated by Django 3.2.8 on 2021-12-10 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnc', '0002_product_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='item_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='model_numbeer',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='upload/'),
        ),
    ]
