# Generated by Django 3.2.8 on 2021-12-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnc', '0002_auto_20211222_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='gmail',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='message',
            field=models.TextField(max_length=250),
        ),
    ]
