# Generated by Django 3.2.8 on 2021-12-11 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cnc', '0003_auto_20211210_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='item_number',
        ),
        migrations.RemoveField(
            model_name='product',
            name='manufacturing_date',
        ),
    ]
