# Generated by Django 3.2.8 on 2021-12-25 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnc', '0003_auto_20211222_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gmail_id', models.EmailField(max_length=254)),
                ('department', models.CharField(max_length=50)),
                ('contact_details', models.TextField(blank=True, verbose_name='Contact Details')),
                ('resume', models.FileField(blank=True, upload_to='upload/')),
            ],
        ),
    ]
