# Generated by Django 3.2.8 on 2021-12-12 19:55

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('cnc', '0004_auto_20211212_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='automatic',
            field=models.BooleanField(default=False, verbose_name='Automatic or Manual'),
        ),
        migrations.AddField(
            model_name='product',
            name='computerized',
            field=models.BooleanField(default=False, verbose_name='Computerized or Manual'),
        ),
        migrations.AddField(
            model_name='product',
            name='detail',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='plc_control',
            field=models.BooleanField(default=False, verbose_name='PLC Control'),
        ),
        migrations.AddField(
            model_name='product',
            name='supply_ability',
            field=models.BooleanField(default=False, verbose_name='Supply Ability'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=10, verbose_name='Enter Price'),
        ),
    ]
