# Generated by Django 3.2.8 on 2021-12-30 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnc', '0005_auto_20211227_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='message',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
