# Generated by Django 3.2.8 on 2021-12-15 16:10

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cnc', '0005_auto_20211213_0125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=50)),
                ('job_location', models.CharField(max_length=50)),
                ('job_description', models.TextField()),
                ('responsibility', models.TextField()),
                ('skillset', models.TextField()),
                ('additional', models.TextField()),
                ('internship', models.BooleanField(default=False, verbose_name='Internship')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 13 digits allowed.", regex='^\\+?1?\\d{9,12}$')])),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('message', models.TextField(blank=True)),
            ],
        ),
    ]
