# Generated by Django 3.2.8 on 2021-12-15 17:32

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('cnc', '0006_career_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='image_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='career',
            name='additional',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='career',
            name='job_description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='career',
            name='responsibility',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='career',
            name='skillset',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
