# Generated by Django 3.2.8 on 2022-01-02 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cnc', '0008_alter_contact_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerapplication',
            name='career',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cnc.career'),
        ),
    ]
