# Generated by Django 3.2.8 on 2022-01-02 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cnc', '0009_careerapplication_career'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cnc.product'),
        ),
    ]
