# Generated by Django 3.2.8 on 2022-01-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnc', '0012_career_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video_url',
            field=models.URLField(max_length=300, null=True),
        ),
    ]
