# Generated by Django 3.2.8 on 2022-01-03 15:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cnc', '0014_auto_20220103_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='date_book',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='careerapplication',
            name='date_upload',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='contact',
            name='date_contact',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
